In [1]:
import numpy as np


In [2]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [5]:
arr=np.array([[1,2,3,4],[2,3,4,5]])
print(arr)

[[1 2 3 4]
 [2 3 4 5]]


In [6]:
arr=np.array([[[1,2,3,4],[2,3,4,5]],[[1,2,3,4],[2,3,4,5]]])
print(arr)

[[[1 2 3 4]
  [2 3 4 5]]

 [[1 2 3 4]
  [2 3 4 5]]]


In [8]:
arr1=np.array(1)
arr2=np.array([[1,2,3,4],[2,3,4,5]])
arr3=np.array([1,2,3,4])

In [9]:
arr1.ndim

0

In [10]:
arr2.ndim

2

In [11]:
arr3.ndim

1

In [12]:
arr3=np.array([[[1,2,3,4],[2,3,4,5]],[[1,2,3,4],[2,3,4,5]]])

In [13]:
arr3.ndim

3

In [16]:
arr4=np.array([1,2,3,4],ndmin=3)
print(arr4)

[[[1 2 3 4]]]


In [17]:
arr4.ndim

3

# NumPy Array Slicing

In [22]:
np.array(arr[2:4])

array([], shape=(0, 2, 4), dtype=int32)

In [23]:
print(arr[1:3])

[[[1 2 3 4]
  [2 3 4 5]]]


In [24]:
print(arr[1:])

[[[1 2 3 4]
  [2 3 4 5]]]


In [25]:
arr=np.array([1,2,3,4])
print(arr[1:3])

[2 3]


In [27]:
print(arr[1:])

[2 3 4]


In [28]:
print(arr[:3])

[1 2 3]


In [29]:
arr3=np.array([[[1,2,3,4],[2,3,4,5]],[[1,2,3,4],[2,3,4,5]]])

In [40]:
print(arr3[1,2,1:3])

IndexError: index 2 is out of bounds for axis 1 with size 2

In [41]:
arr6=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [42]:
print(arr6[1,1:4])

[7 8 9]
