In [1]:
import numpy as np

In [2]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
arr1=np.ones(3)

In [7]:
arr1

array([1., 1., 1.])

In [8]:
arr1=np.ones((3,4),dtype=int)

In [9]:
print(arr1)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [10]:
arr1=np.ones((3,4),dtype=str)

In [11]:
arr1

array([['1', '1', '1', '1'],
       ['1', '1', '1', '1'],
       ['1', '1', '1', '1']], dtype='<U1')

In [12]:
arr1=np.zeros((2,4))

In [13]:
arr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
arr1=np.zeros((2,4),dtype=bool)

In [15]:
arr1

array([[False, False, False, False],
       [False, False, False, False]])

# arange

In [16]:
arr2=np.array([1,2,3,4,5,6])
print(arr2)

[1 2 3 4 5 6]


In [20]:
newarr2=np.arange(1,15,5)

In [21]:
newarr2

array([ 1,  6, 11])

In [22]:
newarr2=np.arange(1,15,2)
newarr2

array([ 1,  3,  5,  7,  9, 11, 13])

# linspace()

In [23]:
arr3=np.linspace(1,4,3)
arr3

array([1. , 2.5, 4. ])

# ravel

In [30]:
arr4=np.array([[1,2,3,4],[5,6,7,8]])
print(arr4)

[[1 2 3 4]
 [5 6 7 8]]


In [31]:
arr4.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])

# transpose

In [34]:
arr4.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [35]:
arr5=np.arange(1,15,2)

In [36]:
arr5

array([ 1,  3,  5,  7,  9, 11, 13])

In [39]:
arr5=np.arange(1,17,2).reshape(2,2,2)

In [40]:
arr5

array([[[ 1,  3],
        [ 5,  7]],

       [[ 9, 11],
        [13, 15]]])

In [41]:
arr6=np.arange(1,17,2).reshape(2,2,2)
print(arr6)

[[[ 1  3]
  [ 5  7]]

 [[ 9 11]
  [13 15]]]


In [42]:
arr5+arr6

array([[[ 2,  6],
        [10, 14]],

       [[18, 22],
        [26, 30]]])

In [43]:
arr5-arr6

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

In [44]:
arr5 @ arr6

array([[[ 16,  24],
        [ 40,  64]],

       [[224, 264],
        [312, 368]]])

In [45]:
arr5.max()

15

In [46]:
arr5.max(axis=0)

array([[ 9, 11],
       [13, 15]])

In [47]:
arr5.max(axis=1)

array([[ 5,  7],
       [13, 15]])

In [48]:
arr5.min(axis=0)

array([[1, 3],
       [5, 7]])

In [49]:
arr5.min(axis=1)

array([[ 1,  3],
       [ 9, 11]])

In [53]:
arr5.argmax()

7

In [54]:
arr5.argmin()

0

In [55]:
np.sum(arr5)

64

In [57]:
np.mean(arr5,axis=1)

array([[ 3.,  5.],
       [11., 13.]])

In [58]:
np.sqrt(arr5)

array([[[1.        , 1.73205081],
        [2.23606798, 2.64575131]],

       [[3.        , 3.31662479],
        [3.60555128, 3.87298335]]])

In [59]:
np.std(arr5)

4.58257569495584

In [60]:
np.exp(arr5)

array([[[2.71828183e+00, 2.00855369e+01],
        [1.48413159e+02, 1.09663316e+03]],

       [[8.10308393e+03, 5.98741417e+04],
        [4.42413392e+05, 3.26901737e+06]]])