In [1]:
import numpy as np

In [2]:
np.random.random(1)

array([0.63927266])

In [3]:
np.random.random(12)

array([0.467287  , 0.70309057, 0.55633351, 0.30199252, 0.33642675,
       0.88170508, 0.25729261, 0.77948958, 0.55617489, 0.95013965,
       0.10619385, 0.69781788])

In [6]:
np.random.randint(10)

7

In [12]:
np.random.randint(2,3,(4,4))

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [15]:
np.random.randint(2,3,(3,4,4))

array([[[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]],

       [[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]],

       [[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]]])

In [16]:
np.random.seed(10)

In [17]:
np.random.randint(2,3,(3,4,4))

array([[[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]],

       [[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]],

       [[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]]])